### ISSUE TITLE
ENCA..sky etc.. or any apprent edgcastcdn.net urls, m3u8 files are not working. (Anymore)

### ISSUE THREAD

**Issue by charun-za** [k3oni/plugin.video.world.news.live#14]
ENCA..sky, bbc etc.. or any apparent edgecastcdn.net urls, m3u8 files are not working.
opening the url in a web browser give me a "403 - Forbidden" 
as the beginning of August 2015  (been about a week)
enca being the important one for me.
Thanks!

enca url: (edgecast)
http://wpc.C1A9.edgecastcdn.net/hls-live/20C1A9/enca/ls_satlink/b_,264,528,828,.m3u8

LOG:
http://pastebin.com/gTD30GbC
<pre>
17:43:41 T:1701057568   ERROR: DEBUG:root:Constructed Plugin {'querystring': 'stream_url=http%3A%2F%2Fwpc.C1A9.edgecastcdn.net%2Fhls-live%2F20C1A9%2Fbbc_world%2Fls_satlink%2Fb_%2C264%2C528%2C828%2C.m3u8&Thumb=%2Fhome%2Fosmc%2F.kodi%2Faddons%2Fplugin.video.world.news.live-master%2Fresources%2Fimages%2Fchannels%2Fbbc.png&channel=bbc&Title=BBC+World&action=play_stream&Icon=%2Fhome%2Fosmc%2F.kodi%2Faddons%2Fplugin.video.world.news.live-master%2Fresources%2Fimages%2Fchannels%2Fbbc.png&remote_url=None&use_rtmp=1', 'db_conn': <sqlite3.Connection object at 0x5de85140>, 'args': {'use_rtmp': '1', 'Title': 'BBC World', 'stream_url': 'http://wpc.C1A9.edgecastcdn.net/hls-live/20C1A9/bbc_world/ls_satlink/b_,264,528,828,.m3u8', 'channel': 'bbc', 'action': 'play_stream', 'Icon': '/home/osmc/.kodi/addons/plugin.video.world.news.live-master/resources/images/channels/bbc.png', 'remote_url': None, 'Thumb': '/home/osmc/.kodi/addons/plugin.video.world.news.live-master/resources/images/channels/bbc.png'}, 'handle': 4, 'script_url': 'plugin://plugin.video.world.news.live/'}
17:43:41 T:1701057568  NOTICE: .
17:43:41 T:1664357408  NOTICE: Thread GUIDialogCache start, auto delete: true
17:43:42 T:1956442112   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://wpc.C1A9.edgecastcdn.net/hls-live/20C1A9/bbc_world/ls_satlink/b_,264,528,828,.m3u8
17:43:42 T:1956442112  NOTICE: DVDPlayer: Opening: http://wpc.C1A9.edgecastcdn.net/hls-live/20C1A9/bbc_world/ls_satlink/b_,264,528,828,.m3u8
17:43:42 T:1956442112 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
17:43:42 T:1664357408  NOTICE: Thread CMMALRenderer start, auto delete: false
17:43:42 T:1701057568  NOTICE: Thread DVDPlayer start, auto delete: false
17:43:42 T:1701057568  NOTICE: Creating InputStream
17:43:42 T:1701057568   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
17:43:42 T:1701057568  NOTICE: CCurlFile::FillBuffer - Reconnect, (re)try 1
17:43:43 T:1701057568   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
17:43:43 T:1701057568   ERROR: CCurlFile::CReadState::Connect, didn't get any data from stream.
17:43:43 T:1701057568   ERROR: Open - failed to open source <http://wpc.C1A9.edgecastcdn.net/hls-live/20C1A9/bbc_world/ls_satlink/b_,264,528,828,.m3u8>
</pre>

**Comment by yanxu4780** [comment]
yep,It's not working!~

**Comment by charun-za** [comment]
Seems to be working again! 
going to close this
seems it was a edgecast problem 
cheers!
