### ISSUE TITLE
CNBC Question

### ISSUE THREAD

**Issue by jdmeissner** [k3oni/plugin.video.world.news.live#15]
Hello, don't think this is a problem with the addon, because I see it primarily with CNBC, but not with Bloomberg or other internet based video.  Your thoughts would be appreciated.  

CNBC plays with a lot of intermittent buffering and usually stops after a few minutes. I have these advancedsettings.xml, of course without the comment markup:

    <!<buffermode>1</buffermode>
    <cachemembuffersize>157286400</cachemembuffersize>
    <readbufferfactor>20</readbufferfactor>  -->

The log shows repeatedly CDVDMessageQueue(video)::Get - asked for new data packet, with nothing available.  More below.

Would be grateful for suggestions.

Thank you and greetings from NH.

Jochen

16:15:10 T:140280573372160  NOTICE: -->Python Interpreter Initialized<--
16:15:11 T:140280573372160   ERROR: DEBUG:root:Constructed Plugin {'querystring': 'use_rtmp=1&Title=CNBC&remote_url=None&action=play_stream&Icon=%2Fhome%2Fjdm%2F.xbmc%2Faddons%2Fplugin.video.world.news.live%2Fresources%2Fimages%2Fchannels%2Fcnbc.png&channel=cnbc&Thumb=%2Fhome%2Fjdm%2F.xbmc%2Faddons%2Fplugin.video.world.news.live%2Fresources%2Fimages%2Fchannels%2Fcnbc.png', 'db_conn': <sqlite3.Connection object at 0x7f959c107a28>, 'args': {'Thumb': '/home/jdm/.xbmc/addons/plugin.video.world.news.live/resources/images/channels/cnbc.png', 'channel': 'cnbc', 'Title': 'CNBC', 'action': 'play_stream', 'Icon': '/home/jdm/.xbmc/addons/plugin.video.world.news.live/resources/images/channels/cnbc.png', 'remote_url': None, 'use_rtmp': '1'}, 'handle': 1, 'script_url': 'plugin://plugin.video.world.news.live/'}
16:15:11 T:140280573372160  NOTICE: .
16:15:11 T:140280323307264  NOTICE: Thread GUIDialogCache start, auto delete: true
16:15:11 T:140282188753280  NOTICE: DVDPlayer: Opening: http://origin2.live.web.tv.streamprovider.net/streams/3bc166ba3776c04e987eb242710e75c0/index.m3u8
16:15:11 T:140282188753280 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
16:15:11 T:140280314914560  NOTICE: Thread DVDPlayer start, auto delete: false
16:15:11 T:140280314914560  NOTICE: Creating InputStream
16:15:11 T:140280573372160  NOTICE: Thread FileCache start, auto delete: false
16:15:11 T:140280314914560  NOTICE: Creating Demuxer
16:15:12 T:140280314914560  NOTICE: Opening stream: 0 source: 256
16:15:12 T:140280314914560  NOTICE: Creating video codec with codec id: 28
16:15:12 T:140280314914560  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
16:15:12 T:140280314914560  NOTICE: Creating video thread
16:15:12 T:140280314914560  NOTICE: Opening stream: 1 source: 256
16:15:12 T:140280314914560  NOTICE: Finding audio codec for: 86018
16:15:12 T:140280133052160  NOTICE: Thread DVDPlayerVideo start, auto delete: false
16:15:12 T:140280133052160  NOTICE: running thread: video_thread
16:15:12 T:140280314914560  NOTICE: Creating audio thread
16:15:12 T:140280124659456  NOTICE: Thread DVDPlayerAudio start, auto delete: false
16:15:12 T:140280124659456  NOTICE: running thread: CDVDPlayerAudio::Process()
16:15:12 T:140280124659456  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
16:15:12 T:140280133052160  NOTICE:  fps: 25.000000, pwidth: 640, pheight: 360, dwidth: 640, dheight: 360
16:15:12 T:140280133052160  NOTICE: Display resolution DESKTOP : 1680x1050@ 59.95 - Full Screen (16)
16:15:12 T:140282188753280  NOTICE: Using GL_TEXTURE_2D
16:15:12 T:140282188753280  NOTICE: GL: Selecting Single Pass YUV 2 RGB shader
16:15:12 T:140282188753280  NOTICE: GL: NPOT texture support detected
16:15:12 T:140282188753280  NOTICE: GL: Using GL_ARB_pixel_buffer_object
16:15:12 T:140282184423168  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
16:15:38 T:140280124659456 WARNING: CDVDMessageQueue(audio)::Get - asked for new data packet, with nothing available
16:15:39 T:140280133052160 WARNING: CDVDMessageQueue(video)::Get - asked for new data packet, with nothing available
16:15:39 T:140280124659456 WARNING: CDVDMessageQueue(audio)::Get - asked for new data packet, with nothing available
16:15:39 T:140280133052160 WARNING: CDVDMessageQueue(video)::Get - asked for new data packet, with nothing available
16:15:39 T:140280124659456 WARNING: CDVDMessageQueue(audio)::Get - asked for new data packet, with nothing available
16:15:47 T:140280133052160 WARNING: Previous line repeats 2 times.
16:15:47 T:140280133052160 WARNING: CDVDMessageQueue(video)::Get - asked for new data packet, with nothing available

**Comment by k3oni** [comment]
What's the system os, openelec, linux, windows? Seems that the issue you are seeing could be related to a couple things but because you are seeing it only on CNBC that could be related to the stream url. 

It could be that you aren't getting a good speed for the current CNBC stream, Kodi doesn't like something about the stream, or a possible local network issue(are you wired or wifi??).

**Comment by jdmeissner** [comment]
Thank you, Florian.

I see this issue on Linux Fedora on a powerful desktop as well as on
Openelec on Raspberry PI. All wired Ethernet.   Again, it is only on
CNBC,  which originally made me think it was the stream itself.  Is
there an easy way to test that? 

But it is also intermittent, so I wonder now if it is the load on my
network.  I may be wrong, but it seems that visitors with Apple WiFi
devices on my network make the problem worse.

Anyway,  I don't want to tie you up with some intermittent home network
issue, just thought you might want to know in case you thought it could
be an issue with the stream, affecting others as well.

Thanks for your help.

Jochen

**Comment by jdmeissner** [comment]
For what it's worth, I think I have eliminated the home network issue -
apologies to all my Apple using friends ;-)

I connected my PC directly to the modem and have exactly the same
buffering problem with CNBC, so I don't think there is much I can do. 
Please let me know if there is a flaw in my logic.

Thank you.

**Comment by k3oni** [comment]
Yes, In that case it's probably the stream causing the issue.
