### ISSUE TITLE
Euronews url not found

### ISSUE THREAD

**Issue by iamfrankenstein** [k3oni/plugin.video.world.news.live#5]
Hi,
I experienced problems connecting to Euronews from the Netherlands, after changing the url and recompiling it works again.

changels.py:353
"data.update({'action': 'play_stream', 'Title': 'English', 'stream_url': 'rtsp://ewns-hls-b-stream.hexaglobe.net/rtpeuronewslive/en_vidan750_rtp.sdp'})"

This could mean regional redirect or just a change in euronews system. 
Thx for the great app btw.

**Comment by k3oni** [comment]
Thanks, updated the url in the latest release.
