### ISSUE TITLE
Changes in other forks

### ISSUE THREAD

**Issue by RSully** [k3oni/plugin.video.world.news.live#7]
I noticed samihaq's fork has some different URLs than yours. I am wondering if some of them are more "direct" from the source than others. Just thought I'd mention it. When I have more time I'll look at the diff and see which changes might make the most sense.

**Comment by RSully** [comment]
Also, is there a specific list/place you're sourcing these URLs from?

**Comment by k3oni** [comment]
Most of them are sourced directly from the source of the stream, in case those aren't working or are blocked then google.
