### ISSUE TITLE
CNBC stopped working

### ISSUE THREAD

**Issue by jdmeissner** [k3oni/plugin.video.world.news.live#9]
First of all, thank you for this great plugin!
CNBC stopped working, assume after upgrade to v1.3.8.6
Same problem on my desktop and on Rasberry PI's.
Log from desktop:
09:51:25 T:140318757316352  NOTICE: Thread JobWorker start, auto delete: true
09:51:29 T:140317013358336  NOTICE: Previous line repeats 1 times.
09:51:29 T:140317013358336  NOTICE: Thread LanguageInvoker start, auto delete: false
09:51:29 T:140317013358336  NOTICE: -->Python Interpreter Initialized<--
09:51:29 T:140317013358336   ERROR: DEBUG:root:Constructed Plugin {'querystring': 'use_rtmp=1&Title=CNBC&remote_url=None&action=play_stream&Icon=%2Fhome%2Fjdm%2F.xbmc%2Faddons%2Fplugin.video.world.news.live%2Fresources%2Fimages%2Fchannels%2Fcnbc.png&channel=cnbc&Thumb=%2Fhome%2Fjdm%2F.xbmc%2Faddons%2Fplugin.video.world.news.live%2Fresources%2Fimages%2Fchannels%2Fcnbc.png', 'db_conn': <sqlite3.Connection object at 0x7f9e1438d858>, 'args': {'Thumb': '/home/jdm/.xbmc/addons/plugin.video.world.news.live/resources/images/channels/cnbc.png', 'channel': 'cnbc', 'Title': 'CNBC', 'action': 'play_stream', 'Icon': '/home/jdm/.xbmc/addons/plugin.video.world.news.live/resources/images/channels/cnbc.png', 'remote_url': None, 'use_rtmp': '1'}, 'handle': 37, 'script_url': 'plugin://plugin.video.world.news.live/'}
09:51:29 T:140317013358336  NOTICE: .
09:51:29 T:140318772648384   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://livestation_hls-lh.akamaihd.net/i/cnbc_en@106428/master.m3u8
09:51:29 T:140318772648384  NOTICE: DVDPlayer: Opening: http://livestation_hls-lh.akamaihd.net/i/cnbc_en@106428/master.m3u8
09:51:29 T:140318772648384 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
09:51:29 T:140317038536448  NOTICE: Thread DVDPlayer start, auto delete: false
09:51:29 T:140317038536448  NOTICE: Creating InputStream
09:51:29 T:140317038536448   ERROR: CCurlFile::FillBuffer - Failed: HTTP response code said error(22)
09:51:29 T:140317038536448  NOTICE: CCurlFile::FillBuffer - Reconnect, (re)try 1
09:51:29 T:140317038536448   ERROR: CCurlFile::FillBuffer - Failed: HTTP response code said error(22)
09:51:29 T:140317038536448   ERROR: CCurlFile::CReadState::Connect, didn't get any data from stream.
09:51:29 T:140317038536448   ERROR: Open - failed to open source <http://livestation_hls-lh.akamaihd.net/i/cnbc_en@106428/master.m3u8>
09:51:29 T:140317038536448  NOTICE: Creating Demuxer
09:51:40 T:140317038536448   ERROR: OpenDemuxStream - Error creating demuxer
09:51:40 T:140317038536448  NOTICE: CDVDPlayer::OnExit()
09:51:40 T:140317038536448  NOTICE: CDVDPlayer::OnExit() deleting input stream
09:51:40 T:140318772648384   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.world.news.live/?use_rtmp=1&Title=CNBC&remote_url=None&action=play_stream&Icon=%2Fhome%2Fjdm%2F.xbmc%2Faddons%2Fplugin.video.world.news.live%2Fresources%2Fimages%2Fchannels%2Fcnbc.png&channel=cnbc&Thumb=%2Fhome%2Fjdm%2F.xbmc%2Faddons%2Fplugin.video.world.news.live%2Fresources%2Fimages%2Fchannels%2Fcnbc.png]
09:51:40 T:140318772648384  NOTICE: CDVDPlayer::CloseFile()
09:51:40 T:140318772648384  NOTICE: DVDPlayer: waiting for threads to exit
09:51:40 T:140318772648384  NOTICE: DVDPlayer: finished waiting
09:51:40 T:140318772648384  NOTICE: CDVDPlayer::CloseFile()
09:51:40 T:140318772648384  NOTICE: DVDPlayer: waiting for threads to exit
09:51:40 T:140318772648384  NOTICE: DVDPlayer: finished waiting
09:51:44 T:140317038536448  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by k3oni** [comment]
This should be fixed in the latest version, thanks.

**Comment by jdmeissner** [comment]
Thank you, the update fixed the weird aspect ratio from before as well.

Again, thank you for providing this plugin!

Jochen
